name: Release
on:
  workflow_run:
    workflows: ["Create and publish a Docker image"]
    branches: [main]
    types: 
      - completed

jobs:
 deploy:
    if: github.repository == 'tech4taxes/website'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: Deploy latest image onto Porygon host
        id: deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: 'website'
          file: 'docker-compose.yml'
          host: ${{ secrets.DOCKER_HOST }}
          user: ${{ secrets.DOCKER_USER }}
          port: 22
          ssh_key: ${{ secrets.DOCKER_SSH_KEY }}
          mode: compose
          detach: true
          args: --pull always --remove-orphans --force-recreate
      - name: 'GHCR.io Container Version Cleanup'
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          keep-n-tagged: 20
          delete-untagged: true
