name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called main`.
on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  id-token: write
  packages: write
  attestations: write

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    if: github.repository == 'tech4taxes/website'
    with:
      context: flask
      output: image
      push: true
      labels: 'latest'
      platforms: linux/amd64,linux/arm64
      meta-images: ghcr.io/tech4taxes/website
      meta-tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=raw,tech4taxes-website-latest
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
