name: ci

on:
  pull_request_target:
    types: [ opened, labeled ]

permissions:
  contents: read
  id-token: write
  packages: write
  attestations: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    if: (github.repository == 'tech4taxes/website') && (github.event.label.name == 'staging')
    with:
      context: flask
      output: image
      push: true
      labels: 'latest'
      platforms: linux/amd64,linux/arm64
      meta-images: ghcr.io/tech4taxes/website
      meta-tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=raw,tech4taxes-website-latest-staging
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
