name: Pagespeed Insights test

on:
  workflow_run:
    workflows: ["Create and publish a Docker image"]
    branches: [main]
    types: 
      - completed

jobs:
  pagespeed-insights:
    if: ${{ github.repository == 'tech4taxes/website' && github.event.workflow_run.conclusion == 'success' }}
    name: Run PageSpeed Insights
    runs-on: ubuntu-latest
    steps:
      - name: Pagespeed Insights
        uses: wicksipedia/pagespeed-insights@main
        id: pagespeed-insights
        with:
          url: https://tech4taxes.org
          categories: |
            accessibility
            best_practices
            performance
            SEO
          strategy: mobile
          delayBetweenRetries: 30000
          maximumNumberOfRetries: 4
          key: ${{ secrets.PAGESPEED_INSIGHTS_API_KEY }}
      - name: Checkout main
        uses: actions/checkout@v5
        id: checkout-main
        with:
          ref: main
      - name: Create destination directory
        env:
          BADGE_PATH: badges
        run: mkdir -p "${BADGE_PATH%/*}"
      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v2.0.2
        id: badge
        with:
          label: 'Accessibility'
          status: ${{ steps.pagespeed-insights.outputs.accessibility }}
          color: ${{
            steps.pagespeed-insights.outputs.accessibility > 90 && 'green'              ||
            steps.pagespeed-insights.outputs.accessibility > 80 && 'yellow,green'       ||
            steps.pagespeed-insights.outputs.accessibility > 70 && 'yellow'             ||
            steps.pagespeed-insights.outputs.accessibility > 60 && 'orange,yellow'      ||
            steps.pagespeed-insights.outputs.accessibility > 50 && 'orange'             ||
            steps.pagespeed-insights.outputs.accessibility > 40 && 'red,orange'         ||
            steps.pagespeed-insights.outputs.accessibility > 30 && 'red,red,orange'     ||
            steps.pagespeed-insights.outputs.accessibility > 20 && 'red,red,red,orange' ||
            'red' }}
          path: badges/pagespeed-insights-accessibility.svg
      - name: Upload badge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pagespeed-insights-accessibility-badge
          path: badges/pagespeed-insights-accessibility.svg
          if-no-files-found: error
      - name: Check if any changes to repo state
        id: repo-change-detect
        run: |
          git diff-index --quiet HEAD -- && test -z "$(git ls-files --others --exclude-standard)"
          CHANGES_DETECTED=$?
          echo "changes_detected=${CHANGES_DETECTED}" >> "$GITHUB_OUTPUT"
      - name: Commit badge
        if: ${{ steps.repo-change-detect.outputs.changes_detected == "1" }}
        continue-on-error: false
        env:
          BADGE: badges/pagespeed-insights-accessibility.svg
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "${BADGE}"
          git commit -m "Add/Update pagespeed insights accessibility badge"
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: ${{ success() && steps.repo-change-detect.outputs.changes_detected == "1" }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
